# -*- coding: utf-8 -*-
"""analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jeHQo4G4F0dTlclQ92xjLp45dVpW9YjF
"""

# ============================================================
# CODE FOR THE 3 FIGURES
# ============================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


# ------------------------------------------------------------
# 1. DEMOGRAPHIC TABLE
# ------------------------------------------------------------

# Data from your survey
department_data = {
    "Department": [
        "Computer Science & Engineering (CSE)",
        "Electrical & Electronics Engineering (EEE)",
        "Business Administration (BBA)",
        "Data Science",
        "English",
        "Other"
    ],
    "Count": [72, 24, 18, 12, 10, 4]
}

cgpa_data = {
    "CGPA Range": [
        "3.81–4.00",
        "3.51–3.80",
        "3.01–3.50",
        "2.50–3.00"
    ],
    "Count": [25, 29, 62, 24]
}

gender_data = {
    "Gender": [
        "Male",
        "Female"
    ],
    "Count": [93, 47]
}

age_data = {
    "Age Range": [
        "18–20 years",
        "21–25 years",
        "26–30 years"
    ],
    "Count": [9, 128, 3]
}


# Create dataframes
department_df = pd.DataFrame(department_data)
cgpa_df = pd.DataFrame(cgpa_data)
gender_df = pd.DataFrame(gender_data)
age_df = pd.DataFrame(age_data)


# Print tables
print("\nDEPARTMENT")
print(department_df)

print("\nCGPA RANGE")
print(cgpa_df)

print("\nGENDER")
print(gender_df)

print("\nAGE RANGE")
print(age_df)


# ------------------------------------------------------------
# 2. BOXPLOT OF QUANTITATIVE FEATURES
# ------------------------------------------------------------

# IMPORTANT:
# This creates the same style of boxplot as your image.
#
# If you have raw survey data, replace these arrays with
# your actual numeric survey columns.
#
# Values are based on the 0–4 Likert scale.

boxplot_data = {

    "LLM_Ease": [
        0, 1, 1, 2, 3, 3, 3, 4, 4, 4
    ],

    "LLM_Efficiency": [
        1, 2, 2, 3, 3, 3, 4, 4, 4, 4
    ],

    "LLM_Satisfaction": [
        1, 2, 2, 3, 3, 3, 3, 4, 4, 4
    ],

    "LLM_Use_Frequency": [
        1, 2, 2, 3, 3, 3, 4, 4, 4, 4
    ],

    "Search_Ease": [
        0, 1, 1, 2, 2, 2, 3, 3, 3, 4
    ],

    "Search_Efficiency": [
        0, 1, 1, 2, 2, 2, 3, 3, 3, 4
    ],

    "Search_Satisfaction": [
        1, 2, 2, 3, 3, 3, 3, 4, 4, 4
    ],

    "Search_Use_Frequency": [
        0, 1, 1, 2, 2, 2, 3, 3, 3, 4
    ]

}


# Convert dictionary into dataframe
boxplot_df = pd.DataFrame(boxplot_data)


# Create figure
plt.figure(figsize=(10, 6))


# Horizontal boxplot
plt.boxplot(

    boxplot_df.values,

    vert=False,

    labels=boxplot_df.columns,

    patch_artist=True,

    showmeans=True

)


# Title
plt.title(

    "Boxplot of Quantitative Features",

    fontsize=14

)


# X-axis
plt.xlabel(

    "Likert Score"

)


# X-axis range
plt.xlim(

    -0.2,

    4.2

)


# Grid
plt.grid(

    axis="x",

    linestyle="--",

    alpha=0.5

)


# Save figure
plt.tight_layout()

plt.savefig(

    "boxplot_quantitative_features.png",

    dpi=300,

    bbox_inches="tight"

)


plt.show()


# ------------------------------------------------------------
# 3. PREFERRED TOOL USAGE BAR CHART
# ------------------------------------------------------------

preferred_tool_data = {

    "Tool": [

        "Both (Hybrid use)",

        "LLMs (e.g., ChatGPT)",

        "Search engines (e.g., Google)"

    ],

    "Students": [

        75,

        48,

        17

    ]

}


preferred_df = pd.DataFrame(

    preferred_tool_data

)


# Create figure
plt.figure(figsize=(10, 6))


# Create bars
bars = plt.bar(

    preferred_df["Tool"],

    preferred_df["Students"]

)


# Title
plt.title(

    "Preferred Tool Usage Among Students",

    fontsize=14

)


# Y-axis label
plt.ylabel(

    "Number of Students"

)


# Rotate labels
plt.xticks(

    rotation=20,

    ha="right"

)


# Grid
plt.grid(

    axis="y",

    linestyle="--",

    alpha=0.5

)


# Add values on top of bars
for bar in bars:

    height = bar.get_height()

    plt.text(

        bar.get_x()
        +
        bar.get_width()
        /
        2,

        height + 1,

        str(int(height)),

        ha="center",

        va="bottom",

        fontsize=11

    )


# Save figure
plt.tight_layout()

plt.savefig(

    "preferred_tool_usage.png",

    dpi=300,

    bbox_inches="tight"

)


plt.show()